apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjMmhsYzNSaGF6SXdNems2WjJod1gwdG5ObHBVZW5SeVdWSk9Nbmw2UTA1WWRGbFhNVFpyVDNFeFNUWnpjelE1Y1hsTldBPT0ifX19
type: kubernetes.io/dockerconfigjson
